/**
 * CertifiedPass — Credential Type Definitions
 *
 * This file is the canonical source of truth for all credential-related types
 * shared between the API, frontend, and smart contract integration layer.
 */

// ---------------------------------------------------------------------------
// Enumerations
// ---------------------------------------------------------------------------

/**
 * Supported credential categories. New categories can be added here
 * without requiring any smart contract changes — the contract stores
 * credentialType as a string; the application layer enforces the enum.
 */
export const CREDENTIAL_TYPES = [
  "hackathon",
  "internship",
  "opensource",
  "event",
  "workshop",
  "competition",
] as const;

export type CredentialType = (typeof CREDENTIAL_TYPES)[number];

/**
 * Lifecycle states of a credential.
 * State machine: create → draft → approved → issued → active → revoked
 * A revoked credential can NEVER return to active.
 */
export const CREDENTIAL_STATUSES = [
  "draft",
  "approved",
  "issued",
  "active",
  "revoked",
] as const;

export type CredentialStatus = (typeof CREDENTIAL_STATUSES)[number];

// ---------------------------------------------------------------------------
// Credential metadata — category-specific field sets
// ---------------------------------------------------------------------------

/** Fields shared across ALL credential types */
export interface BaseCredentialFields {
  /** Display title of the credential (e.g. "Hackathon Winner") */
  title: string;
  /** Human-readable name of the holder */
  holderName: string;
  /** Name of the issuing organization */
  issuerName: string;
  /** ISO 8601 date string — when the achievement occurred */
  issuedAt: string;
  /** Optional: brief description of the achievement */
  description?: string;
  /** Optional: array of skills demonstrated */
  skills?: string[];
}

export interface HackathonFields extends BaseCredentialFields {
  credentialType: "hackathon";
  eventName: string;
  achievement: string;
  rank?: number;
  team?: string;
  project?: string;
  organizer?: string;
}

export interface InternshipFields extends BaseCredentialFields {
  credentialType: "internship";
  companyName: string;
  role: string;
  department?: string;
  startDate: string;
  endDate: string;
  completionStatus: "completed" | "ongoing" | "terminated";
}

export interface OpenSourceFields extends BaseCredentialFields {
  credentialType: "opensource";
  organizationName: string;
  repositoryName: string;
  contributionType: string; // e.g. "Feature", "Bug Fix", "Documentation"
  role?: string;
  periodStart: string;
  periodEnd?: string;
  pullRequestRefs?: string[];
  issueRefs?: string[];
}

export interface EventFields extends BaseCredentialFields {
  credentialType: "event";
  eventName: string;
  role: string; // e.g. "Speaker", "Organizer", "Volunteer", "Attendee"
  date: string;
  location?: string;
  contribution?: string;
}

export interface WorkshopFields extends BaseCredentialFields {
  credentialType: "workshop";
  workshopName: string;
  organizer: string;
  topics: string[];
  date: string;
  durationHours?: number;
  completionStatus: "completed" | "partial";
}

export interface CompetitionFields extends BaseCredentialFields {
  credentialType: "competition";
  competitionName: string;
  rank?: number;
  prize?: string;
  category?: string;
  date: string;
  organizer?: string;
}

/** Union type over all credential metadata shapes */
export type CredentialMetadata =
  | HackathonFields
  | InternshipFields
  | OpenSourceFields
  | EventFields
  | WorkshopFields
  | CompetitionFields;

// ---------------------------------------------------------------------------
// Canonical credential — the exact structure that gets hashed
// CRITICAL: Field order here is canonical. canonicalizeCredential() must
// serialize using exactly these fields in exactly this order.
// ---------------------------------------------------------------------------

export interface CanonicalCredential {
  /** Unique credential ID (UUID v4 generated by the API) */
  id: string;
  /** Credential category — enforces the schema above */
  credentialType: CredentialType;
  /** Wallet address of the issuing organization */
  issuerAddress: string;
  /** Wallet address of the holder */
  holderAddress: string;
  /** ISO 8601 timestamp — when the credential was issued */
  issuedAt: string;
  /** All category-specific metadata fields */
  metadata: CredentialMetadata;
  /** Incrementing version for future schema migrations */
  schemaVersion: number;
}

// ---------------------------------------------------------------------------
// AI extraction types
// ---------------------------------------------------------------------------

/**
 * Raw output from the AI extraction service.
 * IMPORTANT: This is UNTRUSTED input. It must be validated against a strict
 * Zod schema (see packages/utils/src/schema.ts) before use.
 */
export interface AIExtractionResult {
  /** The AI's best guess at the credential type */
  credentialType: string;
  /** Confidence score 0–1 for the detected type */
  typeConfidence: number;
  /** Extracted fields — may be partial, null, or incorrectly typed */
  fields: Record<string, unknown>;
  /** AI's reasoning / notes (shown in review UI) */
  reasoning?: string;
  /** Whether the AI flagged any extraction uncertainty */
  hasUncertainty: boolean;
  /** Which specific fields the AI is uncertain about */
  uncertainFields?: string[];
}

/** A single credential draft generated from AI extraction */
export interface CredentialDraft {
  /** Client-side draft ID */
  draftId: string;
  /** The AI-extracted metadata (not yet validated for issuance) */
  extractedData: Partial<CredentialMetadata>;
  /** Which fields were AI-generated (shown with violet tag in review UI) */
  aiGeneratedFields: string[];
  /** Which fields have been manually edited by the issuer */
  humanEditedFields: string[];
  /** Whether the issuer has approved this draft for issuance */
  approved: boolean;
  /** Validation errors, if any */
  validationErrors?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Verification result
// ---------------------------------------------------------------------------

export const VERIFICATION_STATUSES = [
  "VALID",
  "INVALID",
  "REVOKED",
  "ISSUER_UNVERIFIED",
] as const;

export type VerificationStatus = (typeof VERIFICATION_STATUSES)[number];

export interface VerificationResult {
  status: VerificationStatus;
  /** Human-readable explanation of the status — always shown in UI */
  reason: string;
  /** The credential ID that was verified */
  credentialId: string;
  /** On-chain hash retrieved from contract */
  onChainHash?: string;
  /** Hash recalculated from stored metadata */
  calculatedHash?: string;
  /** Whether the two hashes match */
  hashMatch?: boolean;
  /** Whether the issuer is platform-verified */
  issuerVerified?: boolean;
  /** Whether the credential has been revoked */
  isRevoked?: boolean;
  /** Timestamp of revocation, if revoked */
  revokedAt?: string;
  /** Reason for revocation, if revoked */
  revocationReason?: string;
  /** Blockchain transaction hash of the issuance */
  txHash?: string;
  /** Block number of the issuance transaction */
  blockNumber?: number;
  /** Chain ID on which the credential is anchored */
  chainId?: number;
  /** Timestamp of verification check */
  verifiedAt: string;
}
